---
title: "Cracking ggplot2"
output: github_document
html_document:
  df_print: paged
  keep_md: true
  code_fold: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = T, message=F, warning=F, fig.width = 10, fig.height = 10 )
library(dplyr)
library(pander)
library(ggplot2)

########################
#grants DF

gra16 <- readRDS( gzcon(url("https://github.com/DataCapstone/Data-Capstone/blob/master/Raw-Data/NYgra16_counties_named.rds?raw=true")))

graTOTAL <- gra16

#processing the DF

#Removing state grants
x <- gra16$recipient_type == "00: State government"
#table(x)
#FALSE  TRUE 
#18695 11801
gra16 <- gra16[!x,]

options(scipen = 999)
```


##Understanding GG PLOT

```{r}

######################################

#understanding how ggplot plots as a matrix
#ggplot has a automatic grid. x and y are positions, z is a vector for color. 


df <- data.frame(
  x = c(1,1,3,4,5,1), #three 1 values in X, therefore 4 grid squares drawn, look at their z value to know.
  y = c(2,1,4,1,1,4),
  z = c(1,2,3,1,2,3)
)

ggplot(df, aes(x, y)) +
  geom_tile(aes(fill = z))

df <- data.frame(
  x = c(1:6), #three 1 values in X, therefore 4 grid squares drawn, look at their z value to know.
  y = c(1:6),
  z = c(1:6)
)

#GEOM TILE
ggplot(df, aes(x, y)) +
  geom_tile(aes(fill = z)) #tile puts a "tile" on the y number. Here it is writting at 25 a tile, then another ontop on 25 value, and then one at 50.
#this behaves like points.

#GEOM BAR
ggplot(df, aes(x=x, y=y, fill=z)) +
  geom_bar(width = 1, stat = "identity")
#this behaves more like a bar chart

#GEOM RECT
#this one need y and x max and min. and it draws rectangles!
df <- data.frame(
  xmax = c(1:6), #three 1 values in X, therefore 4 grid squares drawn, look at their z value to know.
  xmin = c(2:7),
  ymax = c(1:6),
  ymin = c(1,1),
  z = c(1:2)
)

ggplot(df) +
  geom_rect(aes(fill = z, ymax=ymax, ymin=ymin, 
                  xmax=xmax, xmin=xmin), colour=c("white"))

#now if we include the function coord_polar, we can see that the x axis starts at 12 o clock vertically and then bars grow cirularly, like a race track. y being the size of the degree of that circular growth.

ggplot(df) +
  geom_rect(aes(fill = z, ymax=ymax, ymin=ymin, 
                  xmax=xmax, xmin=xmin), colour=c("white")) +
   coord_polar(theta="y")
```


#Adding captions to the tiles


dat is:

    county.name    Pop MHincome pov.rate Pop.n MHincome.n pov.rate.n
1        Broome 198093    46261       17  -0.2      -0.69        0.8
2      Onondaga 468304    55092       15   0.3      -0.01        0.3
3  St. Lawrence 112011    44705       17  -0.4      -0.81        0.9
4      Sullivan  76330    50710       17  -0.4      -0.35        0.8
5 State Average 317309    55276       14   0.0       0.00        0.0
 
```{r}
#creating my data
x <- dat

df <- data.frame(x = 1, y = c(1:(nrow(x)*2)), z = sort(rep(1:nrow(x),2)))

df <- data.frame(col = 1, row = c(1:(nrow(x)*2)))

#ggplot likes to recieve dataframes for multiple plotting, otherwise it gets confudes. This is why I constructed this DF with the coordinates of where I want the names!
names <- data.frame(col = 1, 
                 row = c(1:nrow(x)*2),
                 name = toupper(levels(x$county.name))
                 )

#GEOM TILE
ggplot(df, aes(x=col, y=row)) +
  geom_tile(fill= "white", color = "white") +
  geom_text(data = names, aes(x= col, y=row, label = name),
            size= 4,
            hjust = .5,
            vjust = .5,
            colour = "grey40") +
  theme_bw() + 
  theme(legend.position = "none",
          axis.title = element_blank(),
          axis.text=element_blank(), 
          axis.ticks=element_blank(),
          panel.grid=element_blank(),
          panel.border = element_blank(),
          legend.title = element_blank()
          )

  
```

