---
title: "Matching Cities"
output: github_document
html_document:
  df_print: paged
  keep_md: true
  code_fold: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = T, message=F, warning=F, fig.width = 10, fig.height = 10 )
library(censusapi)
library(dplyr)
library(pander)
library(geojsonio)
library(sp) #need this to read the json shapes in gplot
#install.packages("MatchIt")
library(MatchIt)

setwd("C:/Users/icps/Dropbox/3. Maxwell/4. Capston")

```


```{r, eval=FALSE}
#CREATING A NYCENSUS COUNTY RDS

# download acs5 2015 for Population, Median Household income, White, Black, Asian, Hispanic or latino, Unemployed, Income < poverty level last 12 months, In Labor Force
censuskey <- "5a9ad013c3692d7dfdd344a9b2b774f36c50b43d"
dat <- getCensus(name="acs5", vintage=2015, key=censuskey, 
                       vars=c("B01001_001E", "B19013_001E", "B01001A_001E","B01001B_001E", "B01001D_001E", "B01001I_001E", "B23025_005E", "B17001_002E", "B23025_002E"), region="county:*", regionin = "state: 36")

colnames(dat)[3:11] <- c("Pop", "MHincome", "White", "Black", "Asian", "Hispanic", "Unemployed", "Poverty", "Labor")

#creating a county.name variable

#getting a DF with the names of the counties and codes.
cou <- read.csv("https://raw.githubusercontent.com/DataCapstone/Data-Capstone/master/Raw-Data/countycodesNY.csv", stringsAsFactors = F)
dat$county.name <- as.factor(dat$county)
levels(dat$county.name) <- as.character(cou$Name)
#I used levels to standardize the names, but another way to do this could be using the match function:
#order <- match(as.numeric(dat$county), cou$Fips)

#ordering the DF
dem <- dat[,c(1:2,12,3:11)]

#making rates
#colnames(dem)
dem$pov.rate <- dem$Poverty/dem$Pop
dem$une.rate <- dem$Unemployed/dem$Labor
dem$whi.rate <- dem$White/dem$Pop
dem$bla.rate <- dem$Black/dem$Pop
dem$asi.rate <- dem$Asian/dem$Pop
dem$his.rate <- dem$Hispanic/dem$Pop

dem$county <- as.numeric(dem$county)

colnames(dem)[2] <- "county.code"

saveRDS(dem, file = "NYcensus.rds")

```

```{r}
#########################Loading DATASETS########################

############Grants DF##########

gra16 <- readRDS( gzcon(url("https://github.com/DataCapstone/Data-Capstone/blob/master/Raw-Data/NYgra16_counties_named.rds?raw=true")))

############Grants DF##########
NYcensus <- readRDS( gzcon(url("https://github.com/DataCapstone/Data-Capstone/blob/master/Raw-Data/NYcensus.rds?raw=true")))

```


#Matchit 
```{r}

#################################################

dat <- NYcensus

#To run matchit we need to have a treatment and control group
#We flag one county as part of the treatment group and the 61 others are assumed as the control

county <- "Tompkins"
x <- dat$county.name == county
dat$Treat <- 0
dat$Treat[x] <- 1

#creating objects
mat.list <- rep(NA,5)
dis <- rep(FALSE, 62)

#pop density
for (i in c(1:5)) {
  mat <- matchit(Treat ~  Pop, data = dat, discard = dis)
  x <- as.numeric(mat$match.matrix)
  dis[x] <- TRUE
  mat.list[i] <- x
  }
x <- paste(1:5, ".", as.character(dat$county.name[mat.list]), ", ", sep = "", collapse = "")
x <- substr(x,1,nchar(x)-2)
x <- paste0("Matches for ", county, ": ", x)
print(x)

#mat <- matchit(Treat ~  Pop + pov.rate, data = dat, discard = dis)
#"Matches for Tompkins: 1.Cattaraugus, 2.Chautauqua, 3.Oswego, 4.St. Lawrence, 5.Fulton"
#poverty rate is the most simliar

#mat <- matchit(Treat ~  pov.rate + Pop, data = dat, discard = dis)
#"Matches for Tompkins: 1.Sullivan, 2.Franklin, 3.Chenango, 4.Steuben, 5.Broome"
#wierd, again poverty is the one with most simlarity


#mat <- matchit(Treat ~  Pop, data = dat, discard = dis)
#"Matches for Tompkins: 1.Putnam, 2.Ontario, 3.Wayne, 4.Jefferson, 5.Chemung"
#efectively shows the simlarity.

```




