---
title: "shiny adapted"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(pander)
library(shiny)
library(censusapi)
library(plotly)

```

```{r}
# Download the data, clean
gra16.named <- readRDS(gzcon(url("https://github.com/DataCapstone/Data-Capstone/blob/master/Raw-Data/NYgra16_counties_named.rds?raw=true")))

codes <- read.csv("https://raw.githubusercontent.com/DataCapstone/Data-Capstone/master/Raw-Data/countycodesNY.csv")

gra16.without.state <- filter(gra16.named , recipient_type != "00: State government")

gra16.2 <- mutate(gra16.without.state, county = as.character(Name))

gra16.3 <- gra16.2[ c("recipient_name" , "recip_cat_type", "county" , "recipient_type" , "fed_funding_amount" , "assistance_type" , "cfda_program_title" , "agency_name" ) ]

x <- gra16.3$recip_cat_type == "i: Private agencies"
gra16.3$recip_cat_type[x] <- "f: Private agencies"

#making recip_cat_type into a factor and changing the levels into more friendly ones
gra16.3$recip_cat_type <- factor(x= gra16.3$recip_cat_type)

levels(gra16.3$recip_cat_type) <- c("Private firms", 
                                "Government",
                                "Public Higher Ed. Inst.",
                                "Private Higher Ed. Inst.",
                                "Nonprofit agencies",
                                "Other")

# clean agency names a bit to be more consistent
simpleCap <- function(x) {
  s <- tolower(x) 
  s <- strsplit(s, " ")[[1]] 
  paste(toupper(substring(s, 1,1)), substring(s, 2), 
  sep="", collapse=" ")
} 
gra16.3$agency_name <-sapply(gra16.3$agency_name, simpleCap)

gra16.3$agency_name<-gsub( "Department Of ", "", as.character(gra16.3$agency_name), n)

saveRDS( gra16.3, "columns_selected.rds" )


#hmm <- readRDS(gzcon(url("https://github.com/DataCapstone/Data-Capstone/blob/master/Raw-Data/NYcensus.rds?raw=true")))
```

```{r}

#Load the population data
population <- readRDS(gzcon(url("https://github.com/DataCapstone/Data-Capstone/blob/master/Raw-Data/NYcensus.rds?raw=true"))) 

```

```{r}

# Aggregation function
agg.county <- function(df , var){
  
ag <- aggregate(df$fed_funding_amount, by= list( df$county, var), FUN = sum  )

colnames(ag) <- c("county", "var", "fund")

  return(ag)
}




# Per capita aggregation function
agg.county.percap <- function(df, df.p , var){
  
ag <- aggregate(df$fed_funding_amount, by= list( df$county, var), FUN = sum  )

colnames(ag) <- c("county", "var", "fund")

ag.pop <- merge(ag , df.p, by.x = "county", by.y = "county.name")

ag.pop.2 <- mutate(ag.pop , percap =  fund / Pop )

ag.pop.3 <- ag.pop.2[c("var", "fund", "percap", "county")]

  return(ag.pop.3)
}




# Per capita aggregation function, statewide
agg.percap <- function(df, df.p, var){
  
ag <- aggregate(df$fed_funding_amount, by= list( var), FUN = sum  )

colnames(ag) <- c("var", "fund")

ag.2 <- mutate(ag , county = "NY Average")

ag.per <- mutate(ag.2 , percap = fund / (sum(df.p$Pop)))

  return(ag.per)
}



# Doughnut plots

source_github <- function( url ) {
  # load package
  require(RCurl)
  
  # read script lines from website and evaluate
  script <- getURL(url, ssl.verifypeer = FALSE)
  eval(parse(text = script), envir=.GlobalEnv)
} 

#load the donutzz function using the RAW link
source_github("https://raw.githubusercontent.com/icps86/Functions/master/krzydonutzz")

```

```{r}

# National Aggregation

ny.grp <- mutate(gra16.3 , assistance_type.2 = ifelse( assistance_type == "04: Project grant", "Project Grants" , "Other Grants" ) )

ny.per <- agg.percap(ny.grp , population , ny.grp$assistance_type.2) #Function

colnames(ny.per)[1] <- "assistance_type.2"

ny.per.2 <- ny.per[c("assistance_type.2", "fund", "percap", "county")]

saveRDS( ny.per.2, "ny_aggregated_assistance.rds" )

```

```{r}

ui <- fluidPage(
      selectizeInput(
        inputId='your_county', 
            label='Select up to 5 counties to compare:', 
            choices= sort(unique(gra16.3$county)),
            selected=c("Onondaga"), 
            multiple = TRUE, 
            options = list(maxItems = 5)
        ),
      
      radioButtons(
        inputId = 'recipient',
          label='Select a recipient:',
          choices = c( sort(unique(as.character(gra16.3$recip_cat_type))))
      ),
  
  plotOutput("percapPlot"), 
  
  plotOutput("recipientPlot"),
  
  plotOutput("agencyPlot"),
  
  dataTableOutput("cfdaTable")
  
  
  ) 


server <- function(input, output) {
  

#Percapita bar plot  
output$percapPlot <- renderPlot({
    
    
gra16.4 <- filter(gra16.3 , county %in% input$your_county )

pop.filtered <- filter(population , county.name %in% input$your_county )

gra16.4.2 <- mutate(gra16.4 , assistance_type.2 = ifelse( assistance_type == "04: Project grant", "Project Grants" , "Other Grants" ) )

gra16.agg <- agg.county.percap(gra16.4.2 , pop.filtered, gra16.4.2$assistance_type.2) #Function

colnames(gra16.agg)[1] <- "assistance_type.2"

gra16.agg.2 <- gra16.agg[c("assistance_type.2", "fund", "percap", "county")]

gra16.agg.3 <- rbind(gra16.agg.2 , ny.per.2)

cols <- c("#00CCFF","#3333FF")

ggplot(gra16.agg.3, aes(x = county, y = percap, fill = assistance_type.2)) + 
  geom_bar(stat = "identity") + 
  labs(x="County", y="Per Capita Funding") +
  ggtitle("Per Capita Federal Funding by County") +
  scale_y_continuous(labels = scales::comma) + 
  scale_fill_manual(values = cols) +   
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_blank() , legend.title = element_blank())
 

  })
  

#Donut recipient plot 
output$recipientPlot <- renderPlot({
  
gra16.4 <- filter(gra16.3 , county %in% input$your_county , assistance_type == "04: Project grant" , fed_funding_amount > 0) #just care about incoming funds for project grants

agg.per <- agg.county(gra16.4, gra16.4$recip_cat_type)

krzydonutzz(x= agg.per, values = "fund", labels = "var", multiple = "county", main = "Federal Project Grant Funding by Recipient", percent.cex = 3)
  
})

output$agencyPlot <- renderPlot({
  
recipient.filter <- filter(gra16.3, recip_cat_type == input$recipient)
  
agency.agg <- aggregate (recipient.filter$fed_funding_amount, by=list(recipient.filter$agency_name, recipient.filter$county), FUN=sum, na.rm=TRUE)
colnames(agency.agg)<- c("Agency", "County_Name", "Federal_Funding")

agg.pop <- merge(agency.agg , population, by.x = "County_Name", by.y = "county.name", all.x=TRUE)

agg.pop.percap <- mutate(agg.pop , percap =  Federal_Funding / Pop )

county.filter <- filter(agg.pop.percap, County_Name %in% input$your_county)
county.filter.small <- subset (county.filter, select=c("County_Name", "Agency", "percap"))

counties.percap.ordered<- county.filter.small[order(county.filter.small$percap), ]

selected<-counties.percap.ordered[unlist(tapply(row.names(counties.percap.ordered), counties.percap.ordered$County_Name, tail, n = 3)), ] 

   ggplot(selected, aes(Agency, percap)) + geom_bar(aes(fill = County_Name), 
position = position_dodge(), stat="identity") +  facet_wrap(~County_Name)+
   theme(legend.position="right", legend.title = 
   element_blank(),axis.title.x=element_blank(), 
   axis.title.y= element_blank()) + coord_flip()








})


output$cfdaTable <- renderDataTable({
  
gra16.4 <- filter(gra16.3 , county %in% input$your_county , assistance_type == "04: Project grant", fed_funding_amount > 0, recip_cat_type == input$recipient) 
  
gra16.5 <- gra16.4[c("county" , "agency_name",  "recipient_name", "recip_cat_type", "cfda_program_title", "fed_funding_amount")]
  
colnames(gra16.5) <- c("County", "Agency", "Recipient", "Recipient Type", "Program Title", "Funding Recieved")

gra16.5

})

 
} 

shinyApp(ui= ui , server = server)

```



