---
title: "shiny with agg functions"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(pander)
library(shiny)
library(censusapi)
library(plotly)

```

```{r}
# Download the data, clean
gra16.named <- readRDS(gzcon(url("https://github.com/DataCapstone/Data-Capstone/blob/master/Raw-Data/NYgra16_counties_named.rds?raw=true")))

codes <- read.csv("https://raw.githubusercontent.com/DataCapstone/Data-Capstone/master/Raw-Data/countycodesNY.csv")

gra16.without.state <- filter(gra16.named , recipient_type != "00: State government")

gra16.2 <- mutate(gra16.without.state, county = as.character(Name))

gra16.3 <- gra16.2[ c("recipient_name" , "recipient_county_code", "county" , "recipient_type" , "fed_funding_amount" , "assistance_type" , "cfda_program_title" , "agency_name" ) ]

  


#Load the population data
censuskey <- "cc0582f55dc6c9f75f5ea92824c86e0ae5d0d5d8"

population.dat <- getCensus(name="acs5", vintage=2015, key=censuskey, 
                       vars=c("B01001_001E"), region="county:*", regionin = "state: 36")

colnames(population.dat) <- c("state","county_code", "population")

population.dat$county_code <- as.numeric(as.character(population.dat$county_code))

population.dat.2 <- merge(population.dat , codes, by.x = "county_code", by.y = "Fips")





# Aggregation function
agg.county <- function(df , var){
  
ag <- aggregate(df$fed_funding_amount, by= list( df$county, var), FUN = sum  )

colnames(ag) <- c("county", "var", "fund")

  return(ag)
}




# Per capita aggregation function
agg.county.percap <- function(df, df.p , var){
  
ag <- aggregate(df$fed_funding_amount, by= list( df$county, var), FUN = sum  )

colnames(ag) <- c("county", "var", "fund")

ag.pop <- merge(ag , df.p, by.x = "county", by.y = "Name")

ag.pop.2 <- mutate(ag.pop , percap =  fund / population )

ag.pop.3 <- ag.pop.2[c("var", "fund", "percap", "county")]

  return(ag.pop.3)
}




# Per capita aggregation function, statewide
agg.percap <- function(df, df.p, var){
  
ag <- aggregate(df$fed_funding_amount, by= list( var), FUN = sum  )

colnames(ag) <- c("var", "fund")

ag.2 <- mutate(ag , county = "NY Average")

ag.per <- mutate(ag.2 , percap = fund / (sum(df.p$population)))

  return(ag.per)
}

```

```{r}

# National Aggregation

ny.grp <- mutate(gra16.3 , assistance_type.2 = ifelse( assistance_type == "04: Project grant", "Project Grants" , "Other Grants" ) )

ny.per <- agg.percap(ny.grp , population.dat.2 , ny.grp$assistance_type.2) #Function

colnames(ny.per)[1] <- "assistance_type.2"

ny.per.2 <- ny.per[c("assistance_type.2", "fund", "percap", "county")]

```

```{r}


# Shiny input, county comparison
selectizeInput( inputId='your_county', 
            label='Select up to 5 counties to compare:', 
            choices= sort(unique(gra16.3$county)),
            selected=c("Onondaga"), 
            multiple = TRUE, 
            options = list(maxItems = 5)
            )

# Shiny output 1: per capita funding, project grants compare

renderPlotly ({

gra16.4 <- filter(gra16.3 , county %in% input$your_county )

pop.filtered <- filter(population.dat.2 , Name %in% input$your_county )

gra16.4.2 <- mutate(gra16.4 , assistance_type.2 = ifelse( assistance_type == "04: Project grant", "Project Grants" , "Other Grants" ) )

gra16.agg <- agg.county.percap(gra16.4.2 , pop.filtered, gra16.4.2$assistance_type.2) #Function

colnames(gra16.agg)[1] <- "assistance_type.2"

gra16.agg.2 <- gra16.agg[c("assistance_type.2", "fund", "percap", "county")]

gra16.agg.3 <- rbind(gra16.agg.2 , ny.per.2)

cols <- c("#00CCFF","#3333FF")

ggplot(gra16.agg.3, aes(x = county, y = percap, fill = assistance_type.2)) + 
  geom_bar(stat = "identity") + 
  labs(x="County", y="Per Capita Funding") +
  ggtitle("Per Capita Federal Funding by County") +
  scale_y_continuous(labels = scales::comma) + 
  scale_fill_manual(values = cols) +   
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_blank() , legend.title = element_blank())

}) 


# Shiny output 2:
renderPlot({
  
gra16.4 <- filter(gra16.3 , county %in% input$your_county )

pop.filtered <- filter(population.dat.2 , Name %in% input$your_county )

agg.per <- agg.county.percap(gra16.4, pop.filtered, gra16.4$recipient_type)

  
  ggplot(data=agg.per, aes(x=var, y=percap)) +
  geom_bar(stat="identity") +
  facet_wrap(~county, ncol = 1) +
  ggtitle("Multiples") 

})

```
